let
    // ... [Previous steps remain the same until Sort Table]
    SourcePath = Excel.CurrentWorkbook(){[Name="MXFile"]}[Content]{0}[Column1],
    ExternalWorkbook = Excel.Workbook(File.Contents(SourcePath), null, true),
    Sheet1_Sheet = ExternalWorkbook{[Item="Sheet1", Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Merged Queries" = Table.NestedJoin(#"Promoted Headers", {"COUNTERPART"}, ListofACtoAddFrmMurex, {"Column1"}, "ListofACtoAddFrmMurex", JoinKind.Inner),
    #"Removed Columns" = Table.RemoveColumns(#"Merged Queries",{"Marketer_Name", "TIME", "SYS.DATE", "Marketer", "Counter Party Long Name", "ENTITY", "PORTFOLIO", "XPOPTPMNT", "TRADER", "SCBENTITY", "BRW_RTE2", "ECP0", "ECP1", "XPTCUR_2", "EP0", "ECPE0", "Fixed / Variable 0", "Fixed / Variable 1", "PER_RET", "OLD_CPTY", "SRC_SYSTEM", "Index1", "Index0", "BRW_MRG2", "BRW_MRG1", "VALID", "CVA_USD", "CTRTY_TYPE", "FAMILY", "BO.SIGN", "CALC_AGENT", "ARCH_LABEL", "Our comment 0", "Our comment 1", "Market Comment", "XPOPTDELIV", "FLAG1", "FLAG0", "XPRMPD", "ST_DATE", "ED_DATE", "IRV", "OSR", "RISK_PORT", "Last MOP Description", "TYPE_1", "TYPE_SUB", "TRN_TYPO", "STRUC_INVL", "TRANCHE_ID", "CFC", "GROUP", "NOTIONAL", "MOP SYSTEM DATE", "Start Date", "BRW_RTE1", "NB.LTI", "Our comment 2", "Doc Id", "NB.EXT", "SCI_ID", "G.ID"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"COUNTERPART", "INSTRUMENT", "BRW_NOMU1", "QTY.NOMINAL", "BRW_NOMU2", "BRW_NOM2", "XPOPTFPRIC", "B/S", "C/P", "TRN.DATE", "EXPIRY", "TYPE", "A/E", "XPOPTCUTOF", "BARRIER0", "BARRIER1", "XPRMPC", "XPTCUR", "XPRMPA", "CURRENCY1", "TP_STATUS", "NB.INT",  "STRUCT_ID", "STRATEGY","ListofACtoAddFrmMurex"}),
    #"Expanded ListofACtoAddFrmMurex" = Table.ExpandTableColumn(#"Reordered Columns", "ListofACtoAddFrmMurex", {"Column2"}, {"ListofACtoAddFrmMurex.Column2"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Expanded ListofACtoAddFrmMurex",{"COUNTERPART"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns1",{"ListofACtoAddFrmMurex.Column2", "INSTRUMENT", "B/S", "C/P","BRW_NOMU1", "QTY.NOMINAL", "BRW_NOMU2", "BRW_NOM2", "XPOPTFPRIC", "TRN.DATE", "EXPIRY", "TYPE", "A/E", "XPOPTCUTOF", "BARRIER0", "BARRIER1", "XPRMPC", "XPTCUR", "XPRMPA", "CURRENCY1", "TP_STATUS", "NB.INT", "STRUCT_ID", "STRATEGY"}),
    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns1", each [#"C/P"] = "C" or [#"C/P"] = "P"),
    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"ListofACtoAddFrmMurex.Column2", "Client"}, {"INSTRUMENT", "CcyPair"}, {"BRW_NOMU1", "BaseCcy"}, {"QTY.NOMINAL", "BaseNot"}, {"BRW_NOMU2", "CounterCcy"}, {"BRW_NOM2", "CounterNot"}, {"XPOPTFPRIC", "Strike"}, {"XPOPTCUTOF", "Cut"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"BaseNot", type text}, {"CounterNot", type text}, {"NB.INT", type text}}), // Set to text for merging
    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Client", Order.Ascending}}),
    #"Replaced Value" = Table.ReplaceValue(#"Sorted Rows","/","",Replacer.ReplaceText,{"CcyPair"}),
    FlipListRaw = Excel.CurrentWorkbook(){[Name="CcyPairsToFlipList"]}[Content]{0}[Column1],
    FlipListCleaned = Text.Split(Text.Replace(FlipListRaw, " ", ""), ","),
    #"Add Flipped Column" = Table.AddColumn(#"Replaced Value", "Flipped", each if List.Contains(FlipListCleaned, Text.Replace([CcyPair], " ", "")) then "Yes" else null),
    #"Apply Flip Logic" = Table.FromRecords(
        Table.TransformRows(#"Add Flipped Column", each 
            if [Flipped] = "Yes" then
                let r = _
                in Record.TransformFields(r, {
                    {"BaseCcy", each r[CounterCcy]},
                    {"CounterCcy", each r[BaseCcy]},
                    {"BaseNot", each r[CounterNot]},
                    {"CounterNot", each r[BaseNot]},
                    {"CcyPair", each Text.End(r[CcyPair], 3) & Text.Start(r[CcyPair], 3)},
                    {"C/P", each if Record.Field(r, "C/P") = "C" then "P" else if Record.Field(r, "C/P") = "P" then "C" else Record.Field(r, "C/P")}
                })
            else _
        )
    ),
    #"Invert B/S" = Table.TransformColumns(#"Apply Flip Logic", {
        {"B/S", each if _ = "B" then "S" else if _ = "S" then "B" else _, type text}
    }),

    // --- NEW LOGIC STARTS HERE ---
    
    // Group rows to identify candidates for combination
    #"Grouped Rows" = Table.Group(#"Invert B/S", {"STRUCT_ID", "STRATEGY"}, {
        "AllData", each _, type table
    }),

    #"Combined FX_KOFW" = Table.TransformRows(#"Grouped Rows", (grp) =>
        let
            Rows = grp[AllData],
            RowCount = Table.RowCount(Rows),
            // Define expected patterns
            RowBC = Table.SelectRows(Rows, each [#"B/S"] = "B" and [#"C/P"] = "C"),
            RowSP = Table.SelectRows(Rows, each [#"B/S"] = "S" and [#"C/P"] = "P"),
            RowBP = Table.SelectRows(Rows, each [#"B/S"] = "B" and [#"C/P"] = "P"),
            RowSC = Table.SelectRows(Rows, each [#"B/S"] = "S" and [#"C/P"] = "C"),
            
            // Logic for Accu combination
            IsAccu = grp[STRATEGY] = "FX_KOFW" and RowCount = 2 and Table.RowCount(RowBC) = 1 and Table.RowCount(RowSP) = 1,
            // Logic for Decu combination
            IsDecu = grp[STRATEGY] = "FX_KOFW" and RowCount = 2 and Table.RowCount(RowBP) = 1 and Table.RowCount(RowSC) = 1,
            
            // Verification that rest of the fields match (using Row 1 vs Row 2)
            FieldsMatch = if (IsAccu or IsDecu) then 
                            let 
                                r1 = Rows{0}, r2 = Rows{1},
                                // Compare specific stable fields
                                match = r1[Client] = r2[Client] and r1[CcyPair] = r2[CcyPair] and r1[Strike] = r2[Strike] and r1[Cut] = r2[Cut]
                            in match 
                          else false,

            Result = if IsAccu and FieldsMatch then
                        let 
                            rB = RowBC{0}, rS = RowSP{0}
                        in 
                        {Record.Combine({rB, [
                            STRUCT_ID = if rB[Barrier0] = 0 then "Accu-g" else "Accu",
                            #"B/S" = "L",
                            BaseNot = Text.Format("#{0}/#{1}", {rB[BaseNot], rS[BaseNot]}),
                            CounterNot = Text.Format("#{0}/#{1}", {rB[CounterNot], rS[CounterNot]}),
                            #"NB.INT" = Text.Format("#{0}/#{1}", {rB[#"NB.INT"], rS[#"NB.INT"]})
                        ]})}
                     else if IsDecu and FieldsMatch then
                        let 
                            rB = RowBP{0}, rS = RowSC{0}
                        in 
                        {Record.Combine({rB, [
                            STRUCT_ID = if rB[Barrier0] = 0 then "Decu-g" else "Decu",
                            #"B/S" = "S",
                            BaseNot = Text.Format("#{0}/#{1}", {rB[BaseNot], rS[BaseNot]}),
                            CounterNot = Text.Format("#{0}/#{1}", {rB[CounterNot], rS[CounterNot]}),
                            #"NB.INT" = Text.Format("#{0}/#{1}", {rB[#"NB.INT"], rS[#"NB.INT"]})
                        ]})}
                     else 
                        Table.ToRecords(Rows) // Don't combine if pattern isn't met
        in 
            Result
    ),
    #"Final Table" = Table.FromRecords(List.Combine(#"Combined FX_KOFW")),
    
    // --- END NEW LOGIC ---

    #"Sort Table" = Table.Sort(#"Final Table", {
        {"Client", Order.Ascending},
        {"CcyPair", Order.Ascending},
        {"Strike", Order.Ascending},
        {"STRUCT_ID", Order.Ascending},
        {"BaseNot", Order.Ascending}, 
        {"B/S", Order.Ascending}
        })
in
    #"Sort Table"